### ISSUE TITLE
vLogInit() function not defined

### ISSUE THREAD

**Issue by mmacedoeu** [OpenTrading/OTMql4Py#2]
Downloaded the Zip from master and copied folder MQL4 following instalation instrutions, tried to execute the test script MQL4/Scripts/OTMql4/OTMql4PyTest.mq4 with error: Cannot call 'OTMql4/OTLibPy27.ex4::iPyInit', 'OTMql4/OTLibPy27.ex4' is not loaded. Trying to compile OTLibPy27.mq4 raises the vLogInit() not defined

**Comment by OpenTrading** [comment]
That's right.

Reread the installation instructions and see if you catch the part about having to
install OTMql4Lib as a prerequisite. If the documentation is unclear on that, let me
know better wording that would clarify the requirement. vLogInit() is defined in there.
