### ISSUE TITLE
Python Anaconda

### ISSUE THREAD

**Issue by Mahdi-Roozbahani** [OpenTrading/OTMql4Py#5]
I have python27 which is installed by Anaconda. Is there anyways that we can connect this API to Anaconda Python? 
I added my Anaconda folder to my environment variable, but it didn't help (python27.dll is in the main folder of Anaconda. However, the other dlls are in different folders)
There are many libraries and packages already installed in Anaconda and would be great if we can access to them.

**Comment by OpenTrading** [comment]
You can use Anaconda but the Python under MT4 knows nothing about Anaconda.
Windows determines how a dynamic executable looks for Dlls, and the easiest
thing to do is copy the python27.dll to the Windows system32 (or equivalent) folder.
In our experience, putting the Dll directory on the PATH is not enough. Perhaps
this is why the standard Python distribution adds the python27.dll to the system32
diectory.

We'll add this advice to the documentation - thanks for the report.

**Comment by OpenTrading** [comment]
Does your Anaconda include Pywin32? If not, that may also be a problem.

We've added the reauirement for pywin32 to the documentation.
