### ISSUE TITLE
There are some wrong calls of header functions

### ISSUE THREAD

**Issue by Mahdi-Roozbahani** [OpenTrading/OTMql4Py#6]
For example in OTMql4Py/MQL4/Libraries/OTMql4/OTPyChart.mq4, you included "#include <OTMql4/OTZmqProcessCmd.mqh>", while there is no such file called OTZmqProcessCmd.mqh.

**Comment by OpenTrading** [comment]
Thanks - you're right - it's a mistake.

That header file is in the OTMql4Zmq package,  but that package depends on this one OTMql4Py.
We'll look into it, but for the moment, just try deleting that #include line.

**Comment by OpenTrading** [comment]
Those includes were dead code that should not have been in there: they've been removed.

Thanks for spotting this.
