### ISSUE TITLE
Fix the path of the include module in Line 12 of OTMql4PyTest.mq4

### ISSUE THREAD

**Issue by Okeanus** [OpenTrading/OTMql4Py#8]
Line 12 of the file OTMql4PyTest.mq4 `#include <OTMql4/OTLibLog.mqh>` must be changed to `#include <OTMql4/OTLibPyLog.mqh>`

**Comment by OpenTrading** [comment]
No I don't think it must be - either will work.

<OTMql4/OTLibLog.mqh> is provided by the OTMQL4Lib project which is a prerequisite.

The OTLibLog.mqh one is basic MQL4 logging and the OTLibPyLog.mqh does it's logging through Python. On Windows the basic one is safer and so it's the default.

If you agree, I'll close the issue.
